rm longestPalindrome.zip
mv longestPalindrome.c countWays.c
mv tests_longestPalindrome.txt tests_countWays.txt
gcc -Wall -O3 countWays.c -o countWays
./countWays 23
./countWays 12
./countWays 11
./countWays 4
./countWays 11
./countWays 24
./countWays 7
./countWays 6
./countWays 22
./countWays 0
./countWays -3
./countWays 14
./countWays 11
./countWays 18
./countWays 1
./countWays 5
./countWays 18
./countWays 17
./countWays 3
./countWays 6
./countWays 14
./countWays 15
./countWays 8
./countWays 10
./countWays 2
./countWays 1
./countWays 2
./countWays 10
./countWays 16
./countWays 11
./countWays 6
./countWays 7
./countWays 24
./countWays 19
./countWays 6
./countWays 4
./countWays asfdgh
./countWays 23
./countWays 16
./countWays 22
./countWays 14
./countWays ñ
./countWays 3
./countWays 7
./countWays 9
./countWays 2
./countWays 3
./countWays 25
./countWays 21
./countWays 13
./countWays 11
./countWays 15
./countWays ++-
./countWays -8
./countWays 12
./countWays 7
./countWays 15
./countWays 3.342567
./countWays 16
./countWays 7
./countWays 22
./countWays 15
./countWays 11
./countWays 17
./countWays 11
./countWays 15
./countWays 6
./countWays 3
./countWays 3
./countWays 6
./countWays 3
./countWays 15
./countWays 24
./countWays 15
./countWays 25
./countWays 17
./countWays 21
./countWays 14
./countWays 22
./countWays 3
./countWays 15
./countWays 13
./countWays 12
./countWays 13
./countWays 6
./countWays 24
./countWays 11
./countWays 19
./countWays 18
./countWays 22
./countWays 19
./countWays 3
./countWays 19
./countWays 2
./countWays 14
./countWays 19
./countWays 15
./countWays 12
./countWays 18
./countWays 2
rm countWays
zip -r countWays.zip countWays.c